dataset:
  repo_id: four_types_merged_with_depth_colorized
  root: Datasets/example/four_types_merged_with_depth_colorized

policy:
  type: act
  device: cuda
  push_to_hub: false
  
  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.top_depth_colorized:
       type: VISUAL
       shape: [3, 480, 640]
  
  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/act_depth
batch_size: 16
steps: 100000
save_freq: 5000
log_freq: 1000

wandb:
  enable: false